### ISSUE TITLE
Create 1, 3 and 5 sentence DSH project statements

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven-team#15]
Each team member to contribute their own suggestions separately, then we can pull them together

**Comment by edwardchalstrey1** [comment]
# Ed's summaries:

## 1 sentence

Data Safe Haven is a cloud-deployable open source software that enables researchers to work with sensitive data in a secure computing environment.

## 3 sentences

Data Safe Haven is an open source piece of software for working with sensitive data in a secure computing environment hosted on the Microsoft Azure cloud.
Anyone can deploy their own Safe Haven, and each institution that does so creates a new one for each research project.
The development team at Turing also manages Safe Havens for various projects at the institute.

## 5 sentences

The Data Safe Haven (DSH) project involves the development and maintenance of an open source piece of software for working with sensitive data.
This software provides a Secure Research Environment (SRE) for computational research and analysis of data too sensitive to be downloaded onto a personal computer.
Anyone can deploy their own Safe Haven, and each institution that does so sets up a single Safe Haven Management environment (SHM) and a new SRE instance for each research project.
Both of these components are created on the Microsoft Azure cloud computing platform, by following the Safe Haven documentation and running the deployment scripts.
The DSH team at Turing also manage SRE deployments for various projects at the institute, as well as "Data Study Groups", which are hackathon-style challenges hosted at the institute where (typically) PhD students work with data from an external provider.

**Comment by edwardchalstrey1** [comment]
# ChatGPT's summaries - not a bad effort:

![Screenshot 2023-01-16 at 15 50 24](https://user-images.githubusercontent.com/5486164/212718867-a637e548-d757-4c56-94b8-85aa9cd1f418.png)

**Comment by martintoreilly** [comment]
Hmm, feels quite generic and some bits are either not really stressed in our publicly facing materials (e.g. advanced encryption) or incorrect (the detailed audit trail of all data access and sharing activities). What happens if you ask the same question about the James Joyce Institute's "Safe Haven"?

**Comment by JimMadge** [comment]
## One sentence

Data Safe Haven is a free and open-source, infrastructure-as-code defined environment for research using sensitive and personal data.

## Three sentences

Data Safe Haven is an open, community driven project to enable research using sensitive and personal data.
A major component of the project is a free and open-source, infrastructure-as-code defined trusted research environment.
The project also outlines processes deigned to maintain security and address organisations information governance requirements.

**Comment by jemrobinson** [comment]
## One sentence

The Data Safe Haven project aims to collaborate with others to produce an open-source, publicly-available, infrastructure-as-code trusted research environment (TRE) that can be used to reproducibly deploy configurable secure environments for productive research on sensitive data.

### Three sentences

The Data Safe Haven project brings together users and providers of sensitive data in order to develop a productive trusted research environment (TRE) that is sufficiently secure and usable to meet both their needs. The main output is a publicly-available, open-source codebase that can be used to reproducibly deploy configurable TREs onto Microsoft's Azure cloud platform. Information governance concerns are also a key concern, so we have developed a series of security tiers that can be used to determine the appropriate security controls for a given project.

### Five sentences

The Data Safe Haven project aims to remove barriers that prevent data analysis from going ahead on sensitive datasets. This means that we work closely with users and data providers to create trusted research environments (TRE) that find the right balance between security controls around data handling and the usability of the environments. Our major output is a publicly-available, open-source infrastructure-as-code repository that can be used to reproducibly deploy TREs onto Microsoft's Azure cloud platform. We have also developed an information governance classification that groups projects into sensitivity categories where the same security controls can be applied to projects in the same category. It is important that our work has national (and international) impact and as such we aim to be a key player in discussions around designing and using TREs, developing standards and ensuring that our work meets these standards.
