### ISSUE TITLE
Estimate AWS cost for TREEHOOSE

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven-team#6]
Use: https://calculator.aws/#/

**Comment by edwardchalstrey1** [comment]
A rough calculation by adding as many of the components in the [TREEHOOSE architecture](https://github.com/alan-turing-institute/TREEHOOSE/blob/main/doc/architecture/Architecture.md) and [service workbench](https://github.com/awslabs/service-workbench-on-aws) diagrams that I can see, difficult to say how useful this estimate is, I mostly left default settings for each component:

![Screenshot 2022-11-10 at 09 53 44](https://user-images.githubusercontent.com/5486164/201059264-43b9761f-747f-4900-a2f1-e74f1121eb4f.png)

**Comment by jemrobinson** [comment]
@edwardchalstrey1 to talk to Tomas and Fede about whether RCP will manage this or would prefer to leave it to us.

**Comment by edwardchalstrey1** [comment]
### Update from RCP 14th Nov 22

- RCP and IT are going back and forth on a standardised way of working for AWS projects
- They are trying to figure out a centralised way of paying for Turing organisation, a big issue is that *overspend* could occur by default if a project isn't shut down once budget is exceeded
- I will check in on progress tomorrow with Fede after RCP meeting

**Comment by manics** [comment]
Approx costs/month. `0` means negligible (most likely because it was covered by the free tier).

## TREEHOOSE TRE (based on actual spend)

|Service|Cost ($)|
|-|-|
|AWS Amplify|0|
|AWS Budgets|0|
|AWS CloudTrail|1|
|AWS Config|3|
|AWS Cost Explorer|2|
|AWS Data Transfer|0|
|AWS Key Management Service|15|
|AWS Lambda|0|
|AWS Step Functions|0|
|AWS X-Ray|0|
|Amazon DynamoDB|15|
|Amazon Elastic File System|0|
|Amazon Simple Notification Service|0|
|Amazon Simple Queue Service|0|
|Amazon Simple Storage Service|2|
|Amazon Virtual Private Cloud|50|
|AmazonCloudWatch|2|
|**Total**|**88**|

I'm not sure why CloudFront is missing from the output but it was 0, comes under the [always free tier](https://aws.amazon.com/cloudfront/pricing/)



## TREEHOOSE DataLake (optional, based on actual spend)

|Service|Cost ($)|
|-|-|
|AWS CloudTrail|1|
|AWS Config|0|
|AWS Cost Explorer|2|
|AWS Data Transfer|0|
|AWS Glue|0|
|AWS Key Management Service|5|
|AWS Lambda|0|
|Amazon Simple Notification Service|0|
|Amazon Simple Queue Service|0|
|Amazon Simple Storage Service|1|
|AmazonCloudWatch|1|
|**Total**|**10**|


## TREEHOOSE compute (estimated using AWS Calculator)

1 user, 40h/week, [t3a.large (2 vcpu, 8 GB RAM)](https://aws.amazon.com/ec2/instance-types/t3/)
https://calculator.aws/#/estimate?id=77cfcb3b3d6d54a480d12fa6ce4bcf9571d5baca

This is the most complicated to estimate:
- EC2 compute is only charged when the VM is running (no charge when it's shutdown)
- EBS storage is charged for if the VM is running or not, if you delete the VM and attached EBS then you won't be charged
- Appstream charges for actual use, + some idle time when it's not in use. In HIC we've done some work on using [Elastic Appstream](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-appstream-2-0-launches-elastic-fleets-serverless-fleet-type/) which is a lot cheaper and faster, we're hoping to submit that upstream.

|Service|Cost ($)|
|-|-|
|Amazon AppStream 2.0|25|
|Amazon EC2|31|
|**Total**|**56**|

Just shout if want to discuss over Zoom

**Comment by edwardchalstrey1** [comment]
Thanks @manics it looks like the rough estimate comes to 88+10+56=154 USD/pcm which is $1,848 annually, not far off the $1,955 in my screenshot above - so perhaps @jemrobinson we should request $2K or $3K to be safe when it comes to it.

Update from RCP: Tomas is in the process of figuring out purchase orders for AWS, but there's a chance this won't be ready soon - Fede advised to check in again later this week

**Comment by edwardchalstrey1** [comment]
@jemrobinson Tomas is giving us $1,000 to use up until the end of March '23

**Comment by tomaslaz** [comment]
RC Team is approving: £1,000 (including VAT) to be spent on AWS by 2022-03-31.

Fede will be in touch with you regarding the management. However, we will ask the DSH team to look after the budget and provide the RC team with a 2-4 weeks' notice if the project is underspending or overspending for the 2022/2023 financial year.

**Comment by edwardchalstrey1** [comment]
Closing this, I can work on #2 when the above is ready @tomaslaz
